[package]
name = "cargo-xbuild-redirector"
version = "0.1.0"
authors = ["yonasj"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
ex = "^0"
platforms = "^0.2"
regex = "^1"
